/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  start: [
    'start',
  ],
  fe: [
    'sveltekit/overview',
    {
      type: 'html',
      value: '<li class="theme-doc-sidebar-item-link theme-doc-sidebar-item-link-level-1 menu__list-item menu-divider"><a class="menu__link">前置技术</a></li>',
    },
    {
      type: 'category',
      label: 'Svelte',
      items: [
        'svelte/overview',
      ],
    },
    {
      type: 'category',
      label: 'JavaScript',
      items: [
        'javascript/overview',
      ],
    },
    {
      type: 'category',
      label: 'TypeScript',
      items: [
        'typescript/overview',
      ],
    },
    {
      type: 'category',
      label: 'HTML',
      items: [
        'html/overview',
      ],
    },
    {
      type: 'category',
      label: 'CSS',
      items: [
        'css/overview',
      ],
    },
  ],
  android: [
    'jetpack-compose/overview',
    {
      type: 'html',
      value: '<li class="theme-doc-sidebar-item-link theme-doc-sidebar-item-link-level-1 menu__list-item menu-divider"><a class="menu__link">前置技术</a></li>',
    },
    {
      type: 'category',
      label: 'Kotlin',
      items: [
        'kotlin/overview',
      ],
    },
  ],
  apple: [
    'swiftui/overview',
    {
      type: 'html',
      value: '<li class="theme-doc-sidebar-item-link theme-doc-sidebar-item-link-level-1 menu__list-item menu-divider"><a class="menu__link">前置技术</a></li>',
    },
    {
      type: 'category',
      label: 'Swift',
      items: [
        'swift/overview',
      ],
    },
  ],
  spring: [
    'spring/overview',
    {
      type: 'html',
      value: '<li class="theme-doc-sidebar-item-link theme-doc-sidebar-item-link-level-1 menu__list-item menu-divider"><a class="menu__link">前置技术</a></li>',
    },
    {
      type: 'link',
      label: 'Kotlin',
      href: '/docs/kotlin/overview',
    },
  ],
  databases: [
    'databases',
    {
      type: 'category',
      label: 'PostgreSQL',
      items: [
        'postgresql/overview',
      ],
    },
    {
      type: 'category',
      label: 'Redis',
      items: [
        'redis/overview',
      ],
    },
  ],
  base: [
    'base',
    {
      type: 'category',
      label: '数据结构与算法',
      items: [
        'data-structures-algorithms/overview',
      ],
    },
    {
      type: 'category',
      label: '设计模式',
      items: [
        'design-patterns/overview',
      ],
    },
    {
      type: 'category',
      label: 'C语言',
      items: [
        'c/overview',
      ],
    },
    {
      type: 'category',
      label: 'C++',
      items: [
        'c++/overview',
      ],
    },
    {
      type: 'category',
      label: '计算机系统',
      items: [
        'cs/overview',
      ],
    },
  ],
};

module.exports = sidebars;
