/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  programming: [
    {
      type: 'doc',
      label: '概览',
      id: 'index'
    },
    {
      type: 'category',
      label: '程序',
      link: {
        type: 'doc',
        id: '程序/index',
      },
      items: [
        {
          type: 'category',
          label: '操作系统',
          link: {
            type: 'doc',
            id: '程序/操作系统/index',
          },
          items: [],
        },
        {
          type: 'category',
          label: '编译器',
          link: {
            type: 'doc',
            id: '程序/编译器/index',
          },
          items: [],
        },
        {
          type: 'category',
          label: '数据库系统',
          link: {
            type: 'doc',
            id: '程序/数据库系统/index',
          },
          items: [],
        },
      ],
    },
    {
      type: 'category',
      label: '语言',
      link: {
        type: 'doc',
        id: '语言/index',
      },
      items: [
        {
          type: 'category',
          label: '机器语言',
          link: {
            type: 'doc',
            id: '语言/机器语言/index',
          },
          items: [],
        },
        {
          type: 'category',
          label: '汇编语言',
          link: {
            type: 'doc',
            id: '语言/汇编语言/index',
          },
          items: [],
        },
        {
          type: 'category',
          label: 'C语言',
          items: [
            {
              type: 'category',
              label: '预处理指令',
              items: [
                '语言/C语言/预处理指令/index',
              ],
            },
            {
              type: 'category',
              label: '词法规则',
              items: [
                '语言/C语言/词法规则/空白',
                '语言/C语言/词法规则/注释',
                '语言/C语言/词法规则/关键字',
                '语言/C语言/词法规则/标识符',
                '语言/C语言/词法规则/常量',
                '语言/C语言/词法规则/字符串字面量',
                '语言/C语言/词法规则/标点符号',
                '语言/C语言/词法规则/头文件名',
                '语言/C语言/词法规则/预处理数字',
                '语言/C语言/词法规则/通用字符名',
              ],
            },
            {
              type: 'category',
              label: '语法规则',
              items: [
                '语言/C语言/语法规则/表达式',
                '语言/C语言/语法规则/声明',
                '语言/C语言/语法规则/语句',
                '语言/C语言/语法规则/外部定义',
              ],
            },
            {
              type: 'category',
              label: '语义规则',
              items: [
                '语言/C语言/语义规则/类型',
                '语言/C语言/语义规则/main函数',
                '语言/C语言/语义规则/作用域',
                '语言/C语言/语义规则/对象的存储期',
                '语言/C语言/语义规则/对齐',
              ],
            },
            {
              type: 'category',
              label: '标准库',
              items: [
                '语言/C语言/标准库/index',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'C++',
          link: {
            type: 'doc',
            id: '语言/C++/index',
          },
          items: [],
        },
        {
          type: 'category',
          label: 'Java',
          link: {
            type: 'doc',
            id: '语言/Java/index',
          },
          items: [],
        },
        {
          type: 'category',
          label: 'JavaScript',
          link: {
            type: 'doc',
            id: '语言/JavaScript/index',
          },
          items: [],
        },
        {
          type: 'category',
          label: 'DSL',
          link: {
            type: 'doc',
            id: '语言/DSL/index',
          },
          items: [],
        },
      ],
    },
    {
      type: 'category',
      label: '设计',
      link: {
        type: 'doc',
        id: '设计/index',
      },
      items: [
        {
          type: 'category',
          label: '架构设计',
          link: {
            type: 'doc',
            id: '设计/架构设计/index',
          },
          items: [],
        },
        {
          type: 'category',
          label: '系统设计',
          link: {
            type: 'doc',
            id: '设计/系统设计/index',
          },
          items: [],
        },
        {
          type: 'category',
          label: '设计模式',
          link: {
            type: 'doc',
            id: '设计/设计模式/index',
          },
          items: [],
        },
        {
          type: 'category',
          label: '算法设计',
          link: {
            type: 'doc',
            id: '设计/算法设计/index',
          },
          items: [],
        },
        {
          type: 'category',
          label: 'UML',
          link: {
            type: 'doc',
            id: '设计/UML/index',
          },
          items: [],
        },
      ],
    },
    {
      type: 'category',
      label: '工程',
      link: {
        type: 'doc',
        id: '工程/index',
      },
      items: [
        {
          type: 'category',
          label: '软件工程',
          link: {
            type: 'doc',
            id: '工程/软件工程/index',
          },
          items: [
            '工程/软件工程/业务调研',
            '工程/软件工程/业务设计',
            '工程/软件工程/系统设计',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '计算机系统',
      link: {
        type: 'doc',
        id: '计算机系统/index',
      },
      items: [
        {
          type: 'category',
          label: '数字电路',
          link: {
            type: 'doc',
            id: '计算机系统/数字电路/index',
          },
          items: [],
        },
        {
          type: 'category',
          label: '组成原理',
          link: {
            type: 'doc',
            id: '计算机系统/组成原理/index',
          },
          items: [],
        },
        {
          type: 'category',
          label: '计算机网络',
          link: {
            type: 'doc',
            id: '计算机系统/计算机网络/index',
          },
          items: [],
        },
      ],
    },
    {
      type: 'category',
      label: '计算机数学',
      link: {
        type: 'doc',
        id: '计算机数学/index',
      },
      items: [
        {
          type: 'category',
          label: '逻辑代数',
          link: {
            type: 'doc',
            id: '计算机数学/逻辑代数/index',
          },
          items: [],
        },
      ],
    },
  ],
};

module.exports = sidebars;
